name: ascii testing

on: push

jobs:

  first_job:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List repo files
      run: ls -ltra .github/workflows

    - name: Execute a shell script
      run: |
        chmod +x ascii.sh
        ./ascii.sh


       