name: ascii testing

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.name}}
      output2: ${{ steps.step2.outputs.age}}

    steps:
      - id: step1
        run: echo "name=Suri" >> "$GITHUB_OUTPUT"

      - id: step2
        run: echo "age=22" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
    - env:
        OUTPUT1: ${{ needs.job1.outputs.output1 }}
        OUTPUT2: ${{ needs.job1.outputs.output2 }}
      run: echo $OUTPUT1 $OUTPUT2
       