name: ascii testing

on: push

jobs:

  build_job:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Printing Vars
      run: echo Username {{ vars.DOCKER_USERNAME}}

    - name: Printing secrets
      run: echo Password {{ secrets.DOCKER_PASSWORD }}


       