name: Testing the github actions

on: push

jobs:

  first_job:
  
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Welcome message
      run: echo 'My first github actions job'

    - name: Listing files
      run: ls

    - name: read readme files
      run: cat README.md



